I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1741, in script
    
Exception: Sayer 'J' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1741, in script
    
  File "C:\Users\PC\Documents\renpy-8.3.7-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\PC\Documents\renpy-8.3.7-sdk\renpy\ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\PC\Documents\renpy-8.3.7-sdk\renpy\ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'J' is not defined.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
ACHJam 1.0
Sun Apr 13 18:40:43 2025
